apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-volume
      containers:
      - name: influxdb
        image: influxdb_img
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/influxdb"
          name: influxdb-persistent-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-volume
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
      app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - name: http
    protocol: TCP
    port: 8086
    targetPort: 8086